on:
  push: {}

jobs:
  decorate:
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        module:
          - module 1
          - module 2
          - module 3
    steps:
      - uses: actions/checkout@v2
      - name: Updated summary
        run: |
          echo "# Hello world, ${{ matrix.module }} report!" >> $GITHUB_STEP_SUMMARY
          echo "|table|with|" >> $GITHUB_STEP_SUMMARY
          echo "|-----|----|" >> $GITHUB_STEP_SUMMARY
          echo "|A    |B   |" >> $GITHUB_STEP_SUMMARY

