on:
  push: {}

jobs:
  decorate:
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        module:
          - module 1
          - module 2
          - module 3
        include:
          - module: module 1
            wait: 6
          - module: module 2
            wait: 3
          - module: module 3
            wait: 1
    steps:
      - uses: actions/checkout@v2
      - run: sleep ${{ matrix.wait }}
      - name: Updated summary
        run: |
          echo "# Hello world, ${{ matrix.module }} report!" >> $GITHUB_STEP_SUMMARY
          echo "|table|with|" >> $GITHUB_STEP_SUMMARY
          echo "|-----|----|" >> $GITHUB_STEP_SUMMARY
          echo "|A    |B   |" >> $GITHUB_STEP_SUMMARY

